version: "3.7"
services:
  master:
    build: .
    image: centralserver
    command: sh /scripts/start.sh
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
      - 8000
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
      - 8000:8000
    volumes:
      - ./dmarket:/dmarket
      - ./scripts:/scripts
      - ./conf/master:/conf
  worker1:
    build: .
    image: centralserver
    command: sh /scripts/start-worker.sh
    hostname: worker
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    depends_on:
      - "master"
    ports:
      - 8081:8081
    volumes:
      - ./scripts:/scripts
      - ./conf/worker:/conf
  db:
    image: postgres
  