version: "3.7"
services:
  master:
    build: .
    image: centralserver-hadoop-test
    command: sh /scripts/start.sh
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    networks:
      static-network:
        ipv4_address: 10.0.197.2
    extra_hosts:
      - "master:10.0.197.2"
    expose:
      - 9870
      - 7077
      - 6066
      - 22
      - 4040
      - 8042
    ports:
      - 9870:9870
      - 6066:6066
      - 7077:7077
      - 8080:8080
      - 8088:8088
      - 8000:8000
      - 18080:18080
      - 4040:4040
      - 8042:8042
    volumes:
      - ./dmarket:/dmarket
      - ./scripts:/scripts
      - ./sample:/sample
      - ./scala:/scala
  db:
    image: postgres
    networks:
      static-network:
        ipv4_address: 10.0.197.5
networks:
  static-network:
    ipam:
      config:
        - subnet: 10.0.197.0/24